version: '3.8'

services:
  win-gallery-postgres:
    build:
      context: ./prisma
      dockerfile: dockerfile
    container_name: win-gallery-db
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
